server:
    port: 9090
spring:
    application:
        name: caprendizaje-microservice
cloud:
    aws:
        credentials:
            access-key: access-key
            secret-key: secret-key
        s3:
            bucket: bucket
        profilepict:
            path: files/profilepics
        curriculum:
            path: files/curriculums
